### ISSUE TITLE
Does not compile with Python 3.8.0a2, PyInterpreterState opaque type

### ISSUE THREAD

**Issue by nascheme** [psycopg/psycopg2#854]
I get the following error when trying to compile:

    psycopg/psycopgmodule.c: In function ‘psyco_is_main_interp’:
    psycopg/psycopgmodule.c:689:18: error: dereferencing pointer to incomplete type ‘PyInterpreterState’ {aka ‘struct _is’}
         while (interp->next)

This occurs for the 'master' branch from github as well.  I believe the correct fix is to use PEP 3121 (Extension Module Initialization and Finalization) APIs so that psycopg can have per-interpreter state.  Within that state, it can keep a cache to the decimal type object.

**Comment by vstinner** [comment]
> I believe the correct fix is to use PEP 3121

Right, it would be nice. But it can require a lot of work.

Just to fix the compilation error, psyco_is_main_inter() can be modified to use the new PyInterpreterState_Main() function introduced in Python 3.7.

**Comment by dvarrazzo** [comment]
@nascheme @vstinner `PyInterpreterState_Main` is not documented, and bear the disclaimer in the source code:

```c
/* Routines for advanced debuggers, requested by David Beazley.
   Don't use unless you know what you are doing! */
```

Maybe you could provide a patch to suggest the correct usage?

Thank you

**Comment by gaurav1999** [comment]
Hi, I try to build, apache superset, where one of the deps is ```psycopg2-binary==2.7.5```
I do have the devel packages, and everything. But I still am getting the error:

```
psycopg/psycopgmodule.c: In function ‘psyco_is_main_interp’:
    psycopg/psycopgmodule.c:689:18: error: invalid use of incomplete typedef ‘PyInterpreterState’ {aka ‘struct _is’}
      689 |     while (interp->next)
          |                  ^~
    psycopg/psycopgmodule.c:690:24: error: invalid use of incomplete typedef ‘PyInterpreterState’ {aka ‘struct _is’}
      690 |         interp = interp->next;
          |                        ^~
    
    It appears you are missing some prerequisite to build the package from source.
    
    You may install a binary package by installing 'psycopg2-binary' from PyPI.
    If you want to install psycopg2 from source, please install the packages
    required for the build and try again.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).
    
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/gaurav/Projects/incubator-superset/env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rmveb1xw/psycopg2-binary/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rmveb1xw/psycopg2-binary/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-qck0nq6q/install-record.txt --single-version-externally-managed --compile --install-headers /home/gaurav/Projects/incubator-superset/env/include/site/python3.8/psycopg2-binary Check the logs for full command output.

```

**Comment by dvarrazzo** [comment]
Support to Python 3.8 was added in psycopg 2.8.4

**Comment by optimostech** [comment]
Any can help me please?

Best match: psycopg2-binary 2.7.4
Processing psycopg2-binary-2.7.4.tar.gz
Writing /tmp/easy_install-_ttdt6d_/psycopg2-binary-2.7.4/setup.cfg
Running psycopg2-binary-2.7.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-_ttdt6d_/psycopg2-binary-2.7.4/egg-dist-tmp-l99_u3nq
psycopg/psycopgmodule.c: In function ‘psyco_is_main_interp’:
psycopg/psycopgmodule.c:685:18: error: dereferencing pointer to incomplete type ‘PyInterpreterState’ {aka ‘struct _is’}
  685 |     while (interp->next)
      |                  ^~

It appears you are missing some prerequisite to build the package from source.

You may install a binary package by installing 'psycopg2-binary' from PyPI.
If you want to install psycopg2 from source, please install the packages
required for the build and try again.

For further information please check the 'doc/src/install.rst' file (also at
<http://initd.org/psycopg/docs/install.html>).

error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by dvarrazzo** [comment]
@optimostech what part of "Support to Python 3.8 was added in psycopg 2.8.4" is not clear to you?

**Comment by tomasz-szymanek** [comment]
> @optimostech what part of "Support to Python 3.8 was added in psycopg 2.8.4" is not clear to you?

This is really rude.

**Comment by dvarrazzo** [comment]
@tomasz-szymanek So are requests demanding help which don't care for the work already used to answer them.

**Comment by free-variation** [comment]
Scusa, ma sei proprio un coglione -- che maniere sono queste?

**Comment by fogzot** [comment]
Even if @dvarrazzo answer was a bit rude, that is not reason for insults. I marked @free-variation comment as hidden.

**Comment by free-variation** [comment]
Vabbe' -- "a bit rude" -- pare che non sia la prima volta, ma fate come volete.

**Comment by Patrick-Chong** [comment]
> I get the following error when trying to compile:
> 
> ```
> psycopg/psycopgmodule.c: In function ‘psyco_is_main_interp’:
> psycopg/psycopgmodule.c:689:18: error: dereferencing pointer to incomplete type ‘PyInterpreterState’ {aka ‘struct _is’}
>      while (interp->next)
> ```
> 
> This occurs for the 'master' branch from github as well. I believe the correct fix is to use PEP 3121 (Extension Module Initialization and Finalization) APIs so that psycopg can have per-interpreter state. Within that state, it can keep a cache to the decimal type object.

Apologies if this is a basic question, but how do we 'use' PEP 3121? As I am facing the same problem while installing psycopg2

**Comment by dvarrazzo** [comment]
@Patrick-Chong the suggestion of using PEP 3121 is addressed to the people writing and maintaining psycopg, not to the people using it. You should look into how to ask pip to install the right version :)

**Comment by lucaswiman** [comment]
If you run into this error on pypy, the following worked for me. 
* Install `psycopg2cffi`.
* Then before you import any database code, run:
```python
from psycopg2cffi import compat
compat.register()
```

Approach taken from this [post](https://makdos-blog.translate.goog/pypy/1307/importerror-psycopg2_psycopg-pyinterpreterstate_main-hatasi-cozumu?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp) (Auto-translated from Turkish.)
