### ISSUE TITLE
Build fails on pypy3/7.3.7 with undeclared PyDateTime_TimeZone_UTC

### ISSUE THREAD

**Issue by jayvdb** [psycopg/psycopg2#1398]
**Before opening this ticket, please confirm that:**
- [x] I am running the latest version of pip, i.e. typing ``pip --version`` you get [this version](https://pypi.org/project/pip/).
- [x] I have read the [installation documentation](https://www.psycopg.org/docs/install.html) and the [frequently asked questions](https://www.psycopg.org/docs/faq.html)
- [x] I am not trying to install `psycopg2-binary` on an Apple M1, for which [binary packages are not supported](https://github.com/psycopg/psycopg2/issues/1286)
- [x] I am not trying to install `psycopg2-binary` in an Alpine Linux Docker image
- [x] If install failed, I typed `pg_config` on the command line and I obtained an output instead of an error.

**Please complete the following information:**
- OS: Darwin 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64
- Psycopg version: 2.9.2
- Python version: 3.7 (pypy3/7.3.7)
- PostgreSQL version: 14.1
- pip version: 21.3.1

```
gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: x86_64-apple-darwin21.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

```
[pipenv.exceptions.InstallError]:     gcc -pthread -arch x86_64 -DNDEBUG -O2 -fPIC -DPSYCOPG_VERSION=2.9.2 (dt dec pq3 ext lo64 lo64) -DPSYCOPG_DEBUG=1 -DPG_VERSION_NUM=140001 -DHAVE_LO64=1 -DPG_VERSION_NUM=140001 -DHAVE_LO64=1 -I/Users/jayvdb/.local/share/virtualenvs/hindsight-backend-jwlq0EAt/include -I/usr/local/Cellar/pypy3/7.3.7/libexec/include -I. -I/usr/local/include -I/usr/local/include/postgresql/server -I/usr/local/Cellar/icu4c/69.1/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/readline/include -c psycopg/typecast.c -o build/temp.macosx-10.7-x86_64-3.7/psycopg/typecast.o
[pipenv.exceptions.InstallError]:     In file included from psycopg/typecast.c:168:
[pipenv.exceptions.InstallError]:     ./psycopg/typecast_datetime.c:115:14: error: use of undeclared identifier 'PyDateTime_TimeZone_UTC'
[pipenv.exceptions.InstallError]:         tzinfo = PyDateTime_TimeZone_UTC;
[pipenv.exceptions.InstallError]:                  ^
[pipenv.exceptions.InstallError]:     1 error generated.
```

The macro in psycopg/typecast_datetime.c introduced in https://github.com/psycopg/psycopg2/commit/f28502663f1c318dd01c975cf70e3dcce544ab3b looks like it needs to be tweaked to allow for this being missing in pypy3/7.3.7

**Comment by mattip** [comment]
Just noticed this now. I added PyDateTime_TimeZone_UTC to PyPy so it will be part of the next release.
